
CREATE DATABASE AppleShoppingWeb;

CREATE TABLE  APPLE_COMMODITY_(
    COMM_NAME_ varchar(255) ,
    COMM_NUMBER_ SUBSTRING NOT NULL PRIMARY KEY ,
    COMM_BOOKAUTHOR_ SUBSTRING ,
    COMM_PRESS_ SUBSTRING ,
    COMM_PUBLISH_ DATE ,
    COMM_PRICE_ INT(30),
    COMM_STOCOMM_STOCK_ NUMBER(255),
    COMM_ADDEDTIME_ TIMESTAMP ,
    COMM_DISMOUNTED_TIME_ TIMESTAMP ,
    COMM_ARCHIVE_TIME_ TIMESTAMP ,
    COMM_ARCHIVER_ SUBSTRING ,
    COMM_ISBN_ SUBSTRING
);

CREATE TABLE APPLE_MEMBER_(
    MEMB_ID_ SUBSTRING ,
    MEMB_ACCOUNT_ SUBSTRING ,
    MEMB_PASSWORD SUBSTRING ,
    MEMB_EMAIL_ SUBSTRING ,
    MEMB_PHONE_ SUBSTRING ,
    MEMB_REGISTER_TIME_ TIMESTAMP ,
    MEMB_ADMIN_ BOOLEAN,
);

CREATE TABLE APPLE_SHOPPING_INVENTORY_(
    INVE_ID_ SUBSTRING ,
    INVE_LIST_ID_ SUBSTRING,
    INVE_NUMBER_ SUBSTRING ,
);

CREATE TABLE APPLE_SHOPPING_LIST_(
    LIST_ID_ SUBSTRING ,
    LIST_MEMBER_ID_ SUBSTRING ,
    LIST_CHECKOUT_ BOOLEAN,
    LIST_ARRIVAL_ BOOLEAN,
);
CREATE TABLE APPLE_DETAIL_ASSOCIATION_(
    ASSO_LIST_ID_ SUBSTRING ,
    ASSO_INVE_ID_ SUBSTRING ,
);
CREATE TABLE APPLE_RETURN_RECORD_(
    RETU_ID_ SUBSTRING ,

);